name: 'get & cache dependencies'
description: 'Get the depdndencies (via npm) and cache them'
inputs:
  cache:
    description: 'weather to cache dependencies or not'
    required: false
    default: 'true'
runs: 
 using: 'composite' 
 steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      if: inputs.cache == 'true'
      with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cache != 'true'
      run: npm ci
      shell: bash